services:
  sparkmaster:
    image: gettyimages/spark:1.3.1-hadoop-2.4
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master
    hostname: sparkmaster
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - vanda_cluster

  sparkworker:
    image: gettyimages/spark:1.3.1-hadoop-2.4
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkmaster:7077
    hostname: sparkworker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - sparkmaster
      - zeppelin
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data:/zeppelin/data
    networks:
      - vanda_cluster

  zeppelin:
    image: dylanmei/zeppelin:latest
    hostname: zeppelin
    environment:
      ZEPPELIN_PORT: 80
      ZEPPELIN_JAVA_OPTS: "-Dspark.driver.port=5432"
      MASTER: spark://sparkmaster:7077
    links:
      - sparkmaster
      - elasticsearch
    expose:
      - 5432
    ports:
      - 80:80
      - 8091:8091
    volumes:
      - ./data:/zeppelin/data
    networks:
      - vanda_cluster

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    networks:
      - vanda_cluster
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - vanda_cluster
    depends_on:
      - elasticsearch

networks:
  vanda_cluster:
    driver: bridge