version: '2'

services:
  master:
    image: gettyimages/spark:latest
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master
    hostname: master
    environment:
      SPARK_MASTER_HOST: spark://master
      SPARK_MASTER_PORT: 7077    
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - vandacluster

  worker:
    image: gettyimages/spark:latest
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_MASTER_HOST: spark://master
      SPARK_MASTER_PORT: 7077
    links:
      - master
      - zeppelin
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./sparkworker/data:/sparkworker/data
    networks:
      - vandacluster

  zeppelin:
    image: dylanmei/zeppelin:latest
    hostname: zeppelin
    environment:
      ZEPPELIN_PORT: 8090
      ZEPPELIN_JAVA_OPTS: "-Dspark.driver.port=5432"
      MASTER: spark://master:7077
    links:
      - master
      - elasticsearch
    expose:
      - 5432
    ports:
      - 8090:8090
      - 8091:8091
    volumes:
      - ./zeppelin/data:/zeppelin/data
    networks:
      - vandacluster

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    networks:
      - vandacluster
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - vandacluster
    depends_on:
      - elasticsearch

networks:
  vandacluster:
    driver: bridge