version: '3'

services:
  master:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /spark/conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    deploy:
        replicas: 1
        update_config:
            parallelism: 1
        restart_policy:
            condition: on-failure
        placement:
            constraints:
                - node.labels.spark-master == yes

  worker:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /spark/conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081
    deploy:
        replicas: 1
        update_config:
            parallelism: 1
        restart_policy:
            condition: on-failure
        placement:
            constraints:
                - node.labels.spark-worker == yes

  zeppelin:
    image: dylanmei/zeppelin:latest
    hostname: zeppelin
    environment:
      ZEPPELIN_PORT: 8090
      ZEPPELIN_JAVA_OPTS: "-Dspark.driver.port=5432"
      MASTER: spark://master:7077
    ports:
      - 8090:8090
      - 8091:8091
    volumes:
      - zeppelin-data:/usr/zeppelin 
    deploy:
        replicas: 1
        update_config:
            parallelism: 1
        restart_policy:
            condition: on-failure
        placement:
            constraints:
                - node.labels.zeppelin == yes

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data 
    deploy:
        replicas: 1
        update_config:
            parallelism: 1
        restart_policy:
            condition: on-failure
        placement:
            constraints:
                - node.labels.elasticsearch == yes

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    hostname: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    deploy:
        replicas: 1
        update_config:
            parallelism: 1
        restart_policy:
            condition: on-failure
        placement:
            constraints:
                - node.labels.kibana == yes
    
volumes:
  elasticsearch-data:
     external:
         name: vanda-elasticsearch-data
  zeppelin-data:
     external:
         name: vanda-zeppelin-data