version: '2'
networks:
  vanda-cluster:
    driver: bridge

services:
  spark-master:
    image: vandatud/spark-master:latest
    hostname: spark-master
    environment:
      SPARK_NO_DAEMONIZE: 1
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
    ports:
      - 4044:4044
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - vanda-cluster

  spark-worker:
    image: vandatud/spark-worker:latest
    hostname: spark-worker
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_NO_DAEMONIZE: 1
    links:
      - spark-master
      - zeppelin
    depends_on:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    networks:
      - vanda-cluster

  zeppelin:
    image: vandatud/zeppelin:latest
    hostname: zeppelin
    environment:
      ZEPPELIN_PORT: 80
      ZEPPELIN_JAVA_OPTS: "-Dspark.driver.port=5432"
      MASTER: spark://spark-master:7077
    links:
      - spark-master
    expose:
      - 5432
    ports:
      - 80:80
      - 8091:8091
    networks:
      - vanda-cluster